### ISSUE TITLE
Usage Limitations, how to work around?

### ISSUE THREAD

**Issue by usamakzafar** [AlexSim93/pull-request-analytics-action#13]
I'm facing the github error (limit 65536 characters).
When using this in for my real repo with multiple contributors, I get this error:

```
RequestError [HttpError]: Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long"}, {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}
```

What's a good workaround I can use? I can see that the report was generated, only the posting failed. Is there anywhere else I could download the MD file from?

**Comment by AlexSim93** [comment]
Right now there are only 2 options that I see.
1. Inputs values. You can change configuration via inputs. Hide unnecessary information. For example, you can use only one method for `AGGREGATE_VALUE_METHODS` or hide some tables via `SHOW_STATS_TYPES` input. Another way to reduce size of the body is to hide users via `HIDE_USERS`. In case you need all information in report, try to split it in different reports via `REPORT_DATE_START` и `REPORT_DATE_END` 
2. You can get markdown string as an output and split it manually. Post it as an issue and comment after it.

I'm aware of this problem. I will handle it later. I hope my options help you.

**Comment by usamakzafar** [comment]
I needed to see the users.. I used the`SHOW_STATS_TYPES` for now, but I still would like to generate the entire data together.
Splitting by dates was going to be my last resort, as I'll have to start aggregating several tables myself.

> You can get markdown string as an output and split it manually. Post it as an issue and comment after it.
🤔 
how can I get the MD as a string?


Thanks for all your efforts btw!

**Comment by usamakzafar** [comment]
🤔
how can I get the MD as a string?

By setting `EXECUTION_OUTCOME` == `output`?

**Comment by AlexSim93** [comment]
Yep!

**Comment by usamakzafar** [comment]
![Screenshot 2023-12-18 at 17 05 53](https://github.com/AlexSim93/pull-request-analytics-action/assets/29094064/3eb4d60b-a426-46c7-a9ef-942f8a5acbaa)

EXECUTION_OUTCOME: output seems to be an invalid input

**Comment by AlexSim93** [comment]
Released fix

**Comment by usamakzafar** [comment]
Super fast! Checking now

**Comment by usamakzafar** [comment]
Well the validation seems to pass, so does the entire workflow. But unfortunately I'm not seeing any output in the console log. Do I need to get it somewhere manually?

![Screenshot 2023-12-18 at 17 36 48](https://github.com/AlexSim93/pull-request-analytics-action/assets/29094064/956cf4fd-ad26-4391-9ba2-3af8bec7bf14)

**Comment by AlexSim93** [comment]
You can access data on the next step via outputs

**Comment by usamakzafar** [comment]
Got it, thanks a lot! Closing this issue
