### ISSUE TITLE
Idea: Lead time to start review

### ISSUE THREAD

**Issue by astronoka** [AlexSim93/pull-request-analytics-action#26]
This is an idea that was discussed in the development team I am a part of.
Wouldn't it be good to know the next value in the period for each worker so we know if his/her workload is high?

- Total number of reviews requested.
- Average time from receipt of review request to start of review. For unreviewed items, use up to the current time.

If someone can't get started on a review, they are probably too busy with other tasks.
We can check in on the Daily Sync event and forward reviews to others.

Thanks for a great tool!

**Comment by AlexSim93** [comment]
Thanks for your idea. I agree It will make report more comprehensive. I have checked API briefly, It seems like I can add this option to action. I will try to implement it soon:)

**Comment by AlexSim93** [comment]
Hi! I have added new features you might be interested in. **Time in draft**, **time to review request** and **conducted review requests** are available in version `v2`.

You can check out all new features and improvements [here](https://github.com/AlexSim93/pull-request-analytics-action/releases/tag/v2.0.0).

I am closing this issue as I think it's implemented!
