### ISSUE TITLE
Add optional list of TOP_LIST_AMOUNT of SIZE (xs/s/m/l/xl) PRs

### ISSUE THREAD

**Issue by adelcast** [AlexSim93/pull-request-analytics-action#52]
**Is your feature request related to a problem? Please describe.**

I really like the PR lists that lets you focus on the TOP_LIST_AMOUNT. On my team, a clear pain point is PR sizes: we aim to go for smaller PRs, avoid moon-shoot ones. 

**Describe the solution you'd like**

An option to get TOP_LIST_AMOUNT of the XL (or configurable) PRs.

**Describe alternatives you've considered**

Instead of a list, we could add a hyperlink to the size headers (xs, s, m, l, xl) with GH search queries, then we wouldn't need a list. However, this may go counter with the existing pattern of keeping things in lists.

**Additional context**

Really like the work you have done here, thanks!. If you provide additional context I could take a stab at getting this implemented.

**Comment by AlexSim93** [comment]
Hi! Do you want to see all XL PR's? The easiest way for me is creating PR's list sorted by size. The other option I had is to create list of PR's with the most important info. But I guess It won't help you in your case. And I think it might be detected by adding labels to PR's. So then you can filter PRs by labels in github and in this action

**Comment by adelcast** [comment]
Hi @AlexSim93, I think the option to get TOP_LIST_AMOUNT of PRs sorted by size should work for my use case. We are starting to use your GH action reports to discuss PR quality/engagement at the beginning of our weekly status meetings. To drive the discussion into focus areas I want to dive deep into the XL PRs, hence the feature request.

**Comment by AlexSim93** [comment]
The list of the largest PRs was added in the latest release. Sorting takes into account both added and deleted lines.

**Comment by adelcast** [comment]
Thanks so much, just tried it and is exactly what I need!
