### ISSUE TITLE
Workflow returning 404 when using Github Enterprise

### ISSUE THREAD

**Issue by gabytal** [AlexSim93/pull-request-analytics-action#57]
**Describe the bug**
Workflow returning 404 when using Github Enterprise

**Expected behavior**
Report should be created

**Configuration**
`
name: "PR Analytics"
env:
  GITHUB_API_URL: https://git.mycompany.com/api/v3
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
permissions:
  issues: write
  contents: read
  pull-requests: read
  
jobs:
  create-report:
    name: "Create report"
    runs-on: [self-hosted]
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_FOR_ISSUE: ${{ github.event.repository.name }}
          GITHUB_OWNER_FOR_ISSUE: ${{ github.repository_owner }}
          GITHUB_OWNERS_REPOS: ${{ github.repository }}
          SHOW_STATS_TYPES: timeline, workload, pr-quality, code-review-engagement
          REVIEW_TIME_INTERVALS: 2,4,6,9,12,18
          TOP_LIST_AMOUNT: 0
          AGGREGATE_VALUE_METHODS: percentile
          PERCENTILE: 75
          HIDE_USERS: dev1, dev2, dev3
          TIMEZONE: Europe/Berlin
          CORE_HOURS_START: 09:00
          CORE_HOURS_END: 18:00
          AMOUNT: 100
          PERIOD_SPLIT_UNIT: months
          EXECUTION_OUTCOME: markdown
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
`

**Logs**
`Run AlexSim93/pull-request-analytics-action@v4
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

RequestError [HttpError]: Rate limiting is not enabled.
    at /runner/_work/_actions/AlexSim93/pull-request-analytics-action/v4/build/index.js:1[29](https://git.mycompany.com/cicd-demo/demo/actions/runs/407753/job/3953151#step:3:30)51:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestWithGraphqlErrorHandling (/runner/_work/_actions/AlexSim93/pull-request-analytics-action/v4/build/index.js:12422:20)
    at async Job.doExecute (/runner/_work/_actions/AlexSim93/pull-request-analytics-action/v4/build/index.js:14704:18) {
  status: 404,
  response: {`
url: 'https://git.company.com/api/v3/rate_limit',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'alt-svc': 'h3=":443"; ma=86[40](https://git.mycompany.com/cicd-demo/demo/actions/runs/407753/job/3953151#step:3:41)0',
      'cache-control': 'no-cache',
      'cf-cache-status': 'DYNAMIC',
      'cf-ray': '8f35c4bf09e053ee-ATL',
      connection: 'keep-alive',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 17 Dec 2024 09:08:26 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',

**Screenshots**

**Additional context**

**Comment by AlexSim93** [comment]
Hi! Have you tried to setup environment variable? Mentioned [here](https://github.com/AlexSim93/pull-request-analytics-action/pull/10). And enterprise server support was added [here](https://github.com/AlexSim93/pull-request-analytics-action/pull/10)

**Comment by gabytal** [comment]
Hi, Yep, env added, and from the error it seems to get my server address.
but still, getting this weird response

**Comment by AlexSim93** [comment]
Seems like in Enterprise Server you can disable rate limiting. I will handle this case this week.

**Comment by AlexSim93** [comment]
Could you check action with `fix/rate-limit-error` branch. I don't have Github Enterprise Server, so I can't properly check it. But it should work

**Comment by gabytal** [comment]
working!!
thank you!
waiting for the official release

**Comment by AlexSim93** [comment]
Fix is released
